### PR TITLE
Some data and structure improvements

### PR DESCRIPTION
**Pull request by antonegorov**
- Added SwapSwop exchange
- Data in tables are sorted by name
- Added "exchanges" route
- Method specified for all routes
- Close <i> html tag

### CODE REVIEW

**Comment by antonegorov** [comment]
Hi, @pluja.
Please pay attention to this Pull request, as there is a lot of desire to make the service cool, and I also know how to write code (Middle).

Thx!

**Comment by pluja** [comment]
Hey @antonegorov thanks for this! I will be taking a look.

As for SwapSwop ~I will need to investigate. As far as I have seen, it looks like a (very) new exchange. So I will have to take a closer look to it!~ will not be listed. Here is the reason:

From [SwapSwop ToS](https://swapswop.io/terms-of-use):
```
3. AML/KYC Procedure

3.1. The Users don’t need to create accounts: you don’t need to register or log in to use the Website.

However, SwapSwop uses an automated risk management system to check all the transactions made by the Users.

3.2. By accepting these Terms you agree to pass through the AML/KYC procedure, which may be applied to you or may be requested by SwapSwop at any time.

3.3. During the AML/KYC procedure, SwapSwop reserves the right to request additional information and documents, including but not limited to scan of your ID document valid in your country and additional information of the funds' origin.

**3.4. In limited cases (such as to verify your identity in order to pass the AML/KYC procedure), we reserve the right to freeze your exchange transaction for any period of time necessary to complete the investigation and AML/KYC procedure.

3.5. If you deny to pass through the AML/KYC procedure or don’t provide SwapSwop with the requested documents and information, SwapSwop has the right to refuse to execute your transactions (current and future).**

3.6. By accepting these Terms, you agree and warrant to provide true, accurate, current and complete information about yourself and take full responsibility for its accuracy, completeness and veracity.

3.7. For more information, read the official SwapSwop's Rules of Anti-Money Laundering and Combating The Financing Terrorism Compliance Control here.
```

I hope you understand that I can't list an exchange that may make a surprise KYC without the option of refund without KYC (see 3.4 and 3.5).

**Comment by antonegorov** [comment]
Thank you for your time. I have a dialogue with the project manager of SwapSwop service and with special attention I will accept any feedback.

About http://kycnot.me/… I have an idea, which may have great potential. I don't want to make that idea public. Are you interested in this? If so, then text me at hi@antonegorov.ru

**Comment by antonegorov** [comment]
> Hey @antonegorov thanks for this! I will be taking a look.
> 
> As for SwapSwop ~I will need to investigate. As far as I have seen, it looks like a (very) new exchange. So I will have to take a closer look to it!~ will not be listed. Here is the reason:
> 
> From [SwapSwop ToS](https://swapswop.io/terms-of-use):
> ```
> 3. AML/KYC Procedure
> 
> 3.1. The Users don’t need to create accounts: you don’t need to register or log in to use the Website.
> 
> However, SwapSwop uses an automated risk management system to check all the transactions made by the Users.
> 
> 3.2. By accepting these Terms you agree to pass through the AML/KYC procedure, which may be applied to you or may be requested by SwapSwop at any time.
> 
> 3.3. During the AML/KYC procedure, SwapSwop reserves the right to request additional information and documents, including but not limited to scan of your ID document valid in your country and additional information of the funds' origin.
> 
> **3.4. In limited cases (such as to verify your identity in order to pass the AML/KYC procedure), we reserve the right to freeze your exchange transaction for any period of time necessary to complete the investigation and AML/KYC procedure.
> 
> 3.5. If you deny to pass through the AML/KYC procedure or don’t provide SwapSwop with the requested documents and information, SwapSwop has the right to refuse to execute your transactions (current and future).**
> 
> 3.6. By accepting these Terms, you agree and warrant to provide true, accurate, current and complete information about yourself and take full responsibility for its accuracy, completeness and veracity.
> 
> 3.7. For more information, read the official SwapSwop's Rules of Anti-Money Laundering and Combating The Financing Terrorism Compliance Control here.
> ```
> 
> I hope you understand that I can't list an exchange that may make a surprise KYC without the option of refund without KYC (see 3.4 and 3.5).

Ok. Thanks for your time! I am very happy with this thorough approach. I will transfer owners of the exchanger this information and ask it to work with their lawyer.

**Comment by antonegorov** [comment]
FYI If you edit your comment, then no notification is received about it

**Comment by pluja** [comment]
@antonegorov Hey, I just sent you a mail. Sorry for the delay!

PS: didn't know about edits, i'll take that into account.

**Comment by antonegorov** [comment]
@pluja hi. Can you check site again? The documents were changed and now everything should be in fine.

**Pull request closed without merging**
