### PR TITLE
Add BlockDX

### PR DESCRIPTION
**Pull request by luusluus**

### CODE REVIEW

**Comment by pluja** [comment]
Do you need to have BLOCK in order to use it? Have you tested it? I need more info to add it. I will also investigate on my own.

**Comment by luusluus** [comment]
You do not need BLOCK to make an order, when you take an order you pay a small fee in BLOCK. I have tested the application. You need both the BlockDX application installed, as well as the Blocknet Full Node Wallet and other Full Node Wallets (e.g. BTC) synced to make trades. I have personally tested by buying LTC with BLOCK and vice versa.

I have personally tested it and it worked for me.

There is also a litewallet available from where you can trade with BlockDX where no full nodes are required (no syncing). However, this is CLI only and no GUI (yet).

**Comment by pluja** [comment]
Ok, thanks. I will make some more investigation before adding it

**Comment by luusluus** [comment]
If you need any more help, just give me a shout. You can get started here: https://docs.blocknet.co/blockdx/setup/

**Comment by luusluus** [comment]
Thanks again for listing BlockDX exchange. It’s great to have a resource for privacy focused exchanges! 

I saw your tweet asking for feedback and I just noticed that the BlockDX "P2P" icon and the tooltip. Are you able to update this? I was also wondering why this pull request was not merged into master.

**Comment by pluja** [comment]
Sure, done!

**Pull request closed without merging**
